### PR TITLE
Update AmpacheApi.php

### LINKED ISSUE #1: Error for connection
At line 123 of AmpacheApi.php, the password must be hashed in sha before sended to server.
So remove line 123
```
$passphrase = hash('sha256', $timestamp . $this->password);
```

And remplace by this
```
$key = hash('sha256', $this->password);
$passphrase = hash('sha256', $timestamp . $key);
```

Pull #3

### PR DESCRIPTION
**Pull request by gloony**
Fix #1 and #2

### CODE REVIEW

**Comment by lachlan-00** [comment]
hey @gloony, i didn't realise this was open, i'll test and merge when i test my remote catalog on current develop.

**Comment by lachlan-00** [comment]
I haven't forgotten about this. it seems like there is an ampache error i need to fix for this to test

```
2020-01-24 14:17:07 [ampache] (log.lib) -> [Runtime Error] PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in file /var/www/html/lib/class/dba.class.php(90) 
2020-01-24 14:17:07 [user] (dba.class) -> Error_query SQL: INSERT INTO `catalog` (`name`, `catalog_type`, `rename_pattern`, `sort_pattern`, `filter_users`, `gather_types`) VALUES (?, ?, ?, ?, ?) 
2020-01-24 14:17:07 [user] (dba.class) -> Error_query MSG: ["HY093",null,null] 
2020-01-24 14:17:07 [user] (catalog.class) -> Insert failed: {"name":"ampache","type":"remote","rename_pattern":"%T - %t","sort_pattern":"%a\/%A","filter_users":"","gather_art":"1","gather_media":"music","uri":"https:\/\/ampache.org","username":"user","password":"123","action":"add_catalog","form_validation":"6a510f9123"}
```

**Comment by lachlan-00** [comment]
@gloony is there something outside of ampache you use so i can test as well while i fix?

**Comment by jeison1946** [comment]
Hello,

Does anyone know how to apply this change from the composer?

**Comment by lachlan-00** [comment]
> Hello,
> 
> Does anyone know how to apply this change from the composer?

do you use dev-master or a release version?

I haven't got a good knowledge of this repo but it does need massive updates

**Comment by lachlan-00** [comment]
i need to work out how to include this in my regular ampache work and get it updated as this is pretty poor for me to not update

**Comment by lachlan-00** [comment]
@gloony i've tested this with ampache remote catalogs and it's working fine
image

I'm going to spend my time on improving this lib out a lot more and supporting api3/4/5 fully in a new release

**Comment by lachlan-00** [comment]
> Hello,
> 
> Does anyone know how to apply this change from the composer?

you can tag 1.0.2 now which is updated with these changes

https://github.com/ampache/ampacheapi-php/releases/tag/1.0.2

**Pull request merged**
