### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by olaulau**
fix auth passphrase (hash password)
fix send_command data decode for json

### CODE REVIEW

**Comment by lachlan-00** [comment]
If the password is hashed in the database why does it need hashing again?

**Comment by olaulau** [comment]
those are the API handshake specs : https://ampache.org/api/
```
$time = time();
$key = hash('sha256', 'mypassword');
$passphrase = hash('sha256', $time . $key);
```
this code was also used in a previous version of the client (1.0.3) but "corrected" in last master commit.

**Comment by olaulau** [comment]
BTW I came to this because master version didn't work anymore, whereas 1.0.3 (the one packagist gives by default) doesn't have this bug (but many others).

**Comment by lachlan-00** [comment]
i think the ampache server also has some bugs with the key setup but this is fine, sorry for taking so long i'm a bit short on OSS time

**Pull request merged**
